### ISSUE TITLE
Question: CSS not applied

### ISSUE THREAD

**Issue by durino13** [2amigos/yiifoundation#2]
Hi. 

First of all, thx for this extension. I am trying to set it up. I have included

// path aliases
    'aliases' => array(
        // yiifoundation configuration
        'foundation' => 'application.extensions.yiifoundation',
    ),  

in main.php and classes are properly loaded, but no CSS is applied to generated html markup. It's just a plain html. 

1.
How do I make sure, foundation css files are loaded?

2.
How do I make sure, they do not conflict with yii css files? Do I still need to css files of yii (like main.css, screen.css, ie.css, etc, etc?)

**Comment by tonydspaniard** [comment]
You need to specifically call `Foundation::register()` if you are not using any widget in your page. If you using a widget, it will register everything. 

For your second question, if you wish to avoid conflicts you need to control everything your self. I would make sure to avoid CClientScript to register any file at all (that includes the automated script registration done by YiiFoundation) and then insert them on your layout file.

**Comment by durino13** [comment]
Works like a charm!

Thx ;)
